#
# Defines environment variables.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Ensure that a non-login, non-interactive shell has a defined environment.
if [[ ( "$SHLVL" -eq 1 && ! -o LOGIN ) && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprofile"
fi


# Java
export JAVA_HOME=$(/usr/libexec/java_home)

# Maven
export MAVEN_OPTS='-Xmx1g -XX:MaxPermSize=256m'

# SBT
export SBT_OPTS='
-XX:+CMSClassUnloadingEnabled
-XX:MaxPermSize=256M
-XX:ReservedCodeCacheSize=192m
'